server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db
    username: workflow_admin
    password: workflow_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
